# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function computes the exponential of a matrix.
#'
#' This functions calls the \code{expm} function from the eponymous package 
#' \pkg{expm}. This is implemented via a registered function call, and does
#' not required explicit linking at the C level. However, the \pkg{expm} package
#' is imported in order to access its registered function at the C level.
#' 
#' As the documentation of package \pkg{expm} states, the underlying implementation
#' borrows from the \pkg{Matrix} package which itself takes it from GNU Octave.
#' @title Compute the exponential of a matrix
#' @param x An numeric matrix
#' @return A numeric matrix
#' @seealso The \pkg{expm} package and its documentation.
#' @author Dirk Eddelbuettel
#' @examples 
#' 
#' ## example is from the vignette in package expm
#' M <- matrix(c(4, 1, 1, 2, 4, 1, 0, 1, 4), 3, 3)
#' 
#' ## expected output
#' expM <- matrix(c(147.8666, 127.7811, 127.7811, 183.7651, 183.7651, 163.6796, 71.79703, 91.88257, 111.96811), 3, 3)
#' 
#' ## we only have the expected result to about six digits
#' all.equal(expm(M), expM, tolerance=1.0e-6)
expm <- function(x) {
    .Call('RcppKalman_expm', PACKAGE = 'RcppKalman', x)
}

kfPredict <- function(x, P, A, Q, B, u) {
    .Call('RcppKalman_kfPredict', PACKAGE = 'RcppKalman', x, P, A, Q, B, u)
}

kfUpdate <- function(x, P, y, H, R) {
    .Call('RcppKalman_kfUpdate', PACKAGE = 'RcppKalman', x, P, y, H, R)
}

ltiDisc <- function(F, L, Q, dt) {
    .Call('RcppKalman_ltiDisc', PACKAGE = 'RcppKalman', F, L, Q, dt)
}

rtsSmoother <- function(M, Plist, A, Q) {
    .Call('RcppKalman_rtsSmoother', PACKAGE = 'RcppKalman', M, Plist, A, Q)
}

